config/routes.rb
Criterion::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root to: 'admin/dashboard#index'
end

app/views/admin/dashboard/_find_course.html.erb
<%= semantic_form_for [:admin, current_admin_user], url: find_course_admin_courses_path, method: :get, html: { id: 'find_course_form' } do |f| %>
  <%= f.label :id, 'Course:', style: 'font-weight:bold' %>
  <div class="clear"></div>
  <%= f.select :id, Course.get_active_with_id, { include_blank: true }, { id: 'course_id', class: 'chosen-select-modal', style: 'width:400px' } %>
  
  <%= f.actions do %>
    <%= f.action :submit, label: 'Find Course' %>
  <% end %>
<% end %>

app/views/admin/dashboard/_find_student.html.erb
<%= semantic_form_for [:admin, current_admin_user], url: find_student_admin_students_path, method: :get, html: { id: 'find_student_form' } do |f| %>
  <%= f.label :id, 'Student:', style: 'font-weight:bold' %>
  <div class="clear"></div>
  <%= f.select :id, Student.get_all_with_id, { include_blank: true }, { id: 'student_id', class: 'chosen-select-modal', style: 'width:400px' } %>
  
  <%= f.actions do %>
    <%= f.action :submit, label: 'Find Student' %>
  <% end %>
<% end %>

app/views/admin/dashboard/_find_teacher.html.erb
<%= semantic_form_for [:admin, current_admin_user], url: find_teacher_admin_teachers_path, method: :get, html: { id: 'find_teacher_form' } do |f| %>
  <%= f.label :id, 'Teacher:', style: 'font-weight:bold' %>
  <div class="clear"></div>
  <%= f.select :id, Teacher.get_all_with_id, { include_blank: true }, { id: 'teacher_id', class: 'chosen-select-modal', style: 'width:400px' } %>
  
  <%= f.actions do %>
    <%= f.action :submit, label: 'Find Teacher' %>
  <% end %>
<% end %>